### PR TITLE
Fix Typos

### PR DESCRIPTION
**Pull request by medikent**
Many files had misspelled words and a few classes had misspelled names.

### CODE REVIEW

**Comment by btl5037** [comment]
Thank you for the contribution.

Before it can be officially reviewed you need to add your signature to the commit's you pushed, you will need to amend each of them individually and add your signature, or squash both commits into a single commit and then do a `git commit --amend --no-edit -s && git push origin master -f`

Changing the function names has had unintended consequences, I'll try to poke around in it a bit tomorrow to see if I can help you figure out the problem, unless you figure it out yourself before then.

Again thank you for the tedious work!

**Comment by medikent** [comment]
Thanks for the tip! This is my first squash and sign.

**Comment by btl5037** [comment]
Looking into why DCO failed again, it looks like there is a bug in DCO verification when doing a squash, can you run `git commit --amend --no-edit --author="medikent <kbull@mediciventures.com>" && git push origin master -f` assuming that is the correct author name and email.

**Comment by mbwhite** [comment]
@medikent  thank you very much for this PR - great work! Happily merge!

Not sure why the changes have altered the code-coverage results; have you been able to run locally to see what isn't being covered?

**Comment by mbwhite** [comment]
@medikent just realised what the problem is.... the `fabric-chaincode-shim/build.gradle` mentions a few classes by name to assign the code coverage %.

These are using the original (mis-spelt) names!

**Comment by medikent** [comment]
@btl5037 Just ran that command, hope it works. @mbwhite I can run coverage locally, haven't yet.

**Comment by btl5037** [comment]
DCO looks good now

**Comment by medikent** [comment]
Does #73 need to be merged in order forthis PR to pass?

**Comment by btl5037** [comment]
You need to edit `fabric-chaincode-shim/build.gradle` to use the correct function names. This file has bad entries in it as well

**Comment by btl5037** [comment]
After editing the file you can do a `git add fabric-chaincode-shim/build.gradle && git commit --amend --no-edit && git push origin master -f`

**Comment by medikent** [comment]
The Jacoco coverage tests pass on my machine. Is the azure pipeline using a cached version of the build script?

**Comment by btl5037** [comment]
I pulled the code and am trying this out myself, what version of gradle are you running locally `gradle -v` and what version of java `java -version`

**Comment by medikent** [comment]
I just got a failure when running `./gradlew build` I didn't get an error when running the Jacoco task separately.

- java version "1.8.0_172"
- Gradle 5.6.2

**Comment by btl5037** [comment]
@mbwhite I don't know what to say about this, why is the InvocationTaskManager showing its not meeting code coverage all of a sudden, does Jacoco only process files that have been updated? Otherwise this should have been hit by anyone opening PR's. We could introduce a temporary rule to lower the barrier on the class, but why all of a sudden is it being hit?

**Comment by medikent** [comment]
I tried looking around to see if I could increase the code coverage and found `InterruptedException`s, `RejectedExecutionException`s, and generic `RuntimeException`s and `Exception` clauses are mostly the things not covered. I would need to know much more about the concurrency model in the SDK to be able to increase test coverage. I would love to learn more about the SDK.

**Comment by medikent** [comment]
I just cherry picked the coverage increase and rules fix by @mbwhite so things should pass this time.

**Comment by mbwhite** [comment]
Thanks for cherry-picking that @medikent.
@btl5037 that occupied most of my Thursday figuring that one out.  

The tl;dr; is that the order of the tests changed, such that the logging wasn't enabled when that test ran. This was just enough to drop the code coverage; the tests weren't sufficiently isolated. 

However getting there wasn't straightforward; I was considering error paths like @medikent . Indeed I still think there's a subtle ordering issue as I get different results when run locally to that in Azure.

**Pull request merged**
