### PR TITLE
NettyGrpcServer -- support mutual TLS

### PR DESCRIPTION
**Pull request by ftokarev**
This PR adds functionality to optionally authenticate clients of the Java chaincode gRPC server

### CODE REVIEW

**Comment by ftokarev** [comment]
@mbwhite excuse me for pinging you directly, but can you have look at this PR?

**Comment by mbwhite** [comment]
@ftokarev thanks for pinging me... 

Could I ask how you identified MutualTLS wasn't working?  As I *thought* I'd tested this locally and it was working.. but knowing if mutual TLS is working I think is hard. 

(aside we'd need to port this to the release-2.2 branch as well)

**Comment by ftokarev** [comment]
@mbwhite correct me if I wrong, my understanding is that in order for Netty to support mutual TLS it needs to be told to authenticate clients, otherwise it is just plain TLS:
```
sslContextBuilder.clientAuth(ClientAuth.REQUIRE);
```

I agree with you that it is hard to verify whether mutual TLS is working or not. I spent some time trying to come with a unit test for that, but ended up verifying it manually by launching the external chaincode and trying to connect to it without a trusted certificate. If you have some pointers about setting up a unit-test for mutual TLS, I'd be happy to give it a try.

**Comment by mbwhite** [comment]
@ftokarev no, you're correct; just gone back and looked at the example I wrote and I'd made a comment on why the RootCA cert wasn't used - this is why.  I never followed up on why. 

As to testing... really don't how to validate it :-) Maybe Wireshark or something to inspect the protocol?

I'm updating my test now with your changes to try out...

**Comment by ftokarev** [comment]
@mbwhite were there any issues with the test?

**Review by mbwhite — APPROVED** [review]
Thankyou for the update - sorry for the delay. I'm happy to merge this.

Would you able to push the same PR to the release-2.2 branch please... can merge this directly.

**Comment by ftokarev** [comment]
Thanks! 

> Would you able to push the same PR to the release-2.2 branch please... can merge this directly.

sure, https://github.com/hyperledger/fabric-chaincode-java/pull/187

**Pull request merged**
