### PR TITLE
Add OpenTelemetry

### PR DESCRIPTION
**Pull request by atoulme**
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>

This adds OpenTelemetry to Fabric Java chaincode.

### CODE REVIEW

**Comment by jt-nti** [comment]
Hi @atoulme, thanks very much for your pull request. Adding metrics to Fabric looks like it could be really useful and I think it would be good to get this proposal reviewed by the wider Fabric community.

There's a [Request For Comments process](https://github.com/hyperledger/fabric-rfcs) which would need to be followed before merging any PRs, however it would probably be a good idea discussing on Rocket Chat and on one of the maintainer calls beforehand. For example to discuss the choice of OpenTelemetry/B3 headers over alternatives etc.

From an implementation point of view, I noticed that the protobuf code had been updated, but that wasn't reflected in a change to the [protos](https://github.com/hyperledger/fabric-protos) project, or the peer code.

Thanks again, and I look forward to hearing from you about taking this proposal forward. James

**Comment by atoulme** [comment]
Thanks James, I look forward to working with you on this!

**Comment by atoulme** [comment]
The RFC is open here for further discussion: https://github.com/hyperledger/fabric-rfcs/pull/42

**Comment by jt-nti** [comment]
@atoulme I'm hoping that your RFC will get a mention at the next maintainers call to get some more visibility

**Comment by atoulme** [comment]
That'd be swell. I've been busy elsewhere, but I can try to join the call to explain what this is all about.

**Comment by jt-nti** [comment]
Sounds good- I think these are the meeting details if you are able to join

https://calendar.google.com/calendar/event?eid=XzY0cWpnYzloNzBxNmliYjllMHNrb2JoaDZrczM[…]IHZzZHEwNmpqYnJkOGE0NDZuYmI3aDdjNmNrMmoyNmk1QGk&ctz=Etc/GMT

**Comment by mbwhite** [comment]
Closing the PR, note because this is a bad idea, but really needs the RFC as discussed above.

**Comment by atoulme** [comment]
@jt-nti @mbwhite please reopen, the RFC was approved.

**Pull request closed without merging**
