### PR TITLE
Fix(security): Path Traversal Bug & Arbitrary Code Execution 

### PR DESCRIPTION
**Pull request by bhaskarvilles**
Primary Changes to ```/fabric-chaincode-integration-test/src/contracts/bare-maven/.mvn/wrapper/MavenWrapperDownloader.java```

### CODE REVIEW

**Review by mbwhite — CHANGES_REQUESTED** [review]
There are lot of changes in this PR;

- the change to fix the java code, this is in the maven wrapper code (which actually shouldn't be checked in) so we really get rid of this `.mvn` directory entirely.
- a lot of the scripts have had permissions changed - these need to run on a Linux CI so need those permissions
- also removal of the test certificates etc. These are for testing.

**Comment by mbwhite** [comment]
@bhaskarvilles the failure of the builds above, I believe, are related to the removal of permissions
@ryjones the h1 link is really an issue in maven and fabric-chaincode-java

**Comment by ryjones** [comment]
> @ryjones the h1 link is really an issue in maven and fabric-chaincode-java

I was merely linking for completeness :)

**Comment by bhaskarvilles** [comment]
@ryjones I invite you as a collaborator please fix the issues.

**Comment by ryjones** [comment]
> @ryjones I invite you as a collaborator please fix the issues.

I can't - please make a new patch that only has your changes

**Comment by mbwhite** [comment]
Hello; I've double checked into the details more. The maven wrapper is found within two locations

```
./fabric-chaincode-integration-test/src/contracts/bare-maven/.mvn
./fabric-chaincode-integration-test/src/contracts/wrapper-maven/.mvn
```

The first - should NOT have the maven wrapper in place, this should be removed, 
The second - should be updated to use the latest maven wrapper that does have this issue. 

@bhaskarvilles are you able to update the PR please?  Thanks for spotting the Maven wrapper was an issue.

**Comment by bhaskarvilles** [comment]
> > @ryjones I invite you as a collaborator please fix the issues.
> 
> I can't - please make a new patch that only has your changes

Let me re Submit the issue with my changes.

**Comment by bhaskarvilles** [comment]
> Hello; I've double checked into the details more. The maven wrapper is found within two locations
> 
> ```
> ./fabric-chaincode-integration-test/src/contracts/bare-maven/.mvn
> ./fabric-chaincode-integration-test/src/contracts/wrapper-maven/.mvn
> ```
> 
> The first - should NOT have the maven wrapper in place, this should be removed, The second - should be updated to use the latest maven wrapper that does have this issue.
> 
> @bhaskarvilles are you able to update the PR please? Thanks for spotting the Maven wrapper was an issue.

I've tried many times, can you help me with this ?

**Comment by mbwhite** [comment]
1) This directory needs to be deleted.
```
./fabric-chaincode-integration-test/src/contracts/bare-maven/.mvn
```


2) Delete this directory, and then from ./fabric-chaincode-integration-test/src/contracts/wrapper-maven directory recreate the wrapper with `mvn wrapper:wrapper`

```
./fabric-chaincode-integration-test/src/contracts/wrapper-maven/.mvn
```

**Comment by bhaskarvilles** [comment]
> 1. This directory needs to be deleted.
> 
> ```
> ./fabric-chaincode-integration-test/src/contracts/bare-maven/.mvn
> ```
> 
> 2. Delete this directory, and then from ./fabric-chaincode-integration-test/src/contracts/wrapper-maven directory recreate the wrapper with `mvn wrapper:wrapper`
> 
> ```
> ./fabric-chaincode-integration-test/src/contracts/wrapper-maven/.mvn
> ```

when ever i was trying to clone again it shows file name too long error.

**Comment by mbwhite** [comment]
> > 1. This directory needs to be deleted.
> > 
> > ```
> > ./fabric-chaincode-integration-test/src/contracts/bare-maven/.mvn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Delete this directory, and then from ./fabric-chaincode-integration-test/src/contracts/wrapper-maven directory recreate the wrapper with `mvn wrapper:wrapper`
> > 
> > ```
> > ./fabric-chaincode-integration-test/src/contracts/wrapper-maven/.mvn
> > ```
> 
> when ever i was trying to clone again it shows file name too long error.

Would you be using Windows command line for this?

**Comment by denyeart** [comment]
Since it had been two weeks, @mbwhite submitted a clean fix at https://github.com/hyperledger/fabric-chaincode-java/pull/254. I'll close this one. Thank you for the report and the contribution!

**Pull request closed without merging**
